# Author: Saba Mansourfar 
# University: Politecnico Di Milano
# Labratory: NearLAB
#     Robot: Omni Phantom

#  **Important Notice**
#  This will load default Omni controllers + some specific controllers

omni_phantom:
  gazebo_ros_control:   
    pid_gains:
      waist: {p: 250,  i: 10, d: 30}
      shoulder: {p: 220,  i: 10, d: 30}
      elbow: {p: 150,  i: 6, d: 20}
      wrist1: {p: 150,  i: 5, d: 12}
      wrist2: {p: 90,  i: 5, d: 10}
      wrist3: {p: 40,  i: 5, d: 7}