# Author: Saba Mansourfar 
# University: Politecnico Di Milano
# Labratory: NearLAB
#     Robot: Omni Phantom

#  **Important Notice**
#  This will load default OmniPhantom controllers + some specific controllers
# ----------- MOVEIT SPECIFIC CONTTROLLERS -------------------
# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: all
  joint_model_group_pose: Docked
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - waist
    - shoulder
    - elbow
    - wrist1
    - wrist2
    - wrist3
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
# ----------- OMNI Control ------------- #
omni_phantom:
  # CONTROLLERS USED IN THE EXAMPLE
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # THIS CONFIGURATION IS ACTUALLY SENDING TAU = K*Q
  joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - waist
      - shoulder
      - elbow
      - wrist1
      - wrist2
      - wrist3
