# Author: Saba Mansourfar 
# University: Politecnico Di Milano
# Labratory: NearLAB
#     Robot: Omni Phantom

#  **Important Notice**
#  This will load default Omni controllers + some specific controllers

omni_phantom:
  # CONTROLLERS USED
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # THIS CONFIGURATION IS ACTUALLY SENDING TAU = K*Q
  joint_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
     - waist
     - shoulder
     - elbow
     - wrist1
     - wrist2
     - wrist3